bessim0 – PLUME
bessim0 Function
16 statements
public function bessim0(x)
Uses
nrtype
nrutil_trim
Calculates the Modified Bessel Function of order zero. Determines I_0(x) e^(-x) instead of I_0(x) to avoid large argument problems.
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(in) :: x
Argument of Modified Bessel Function.
Return Value real(kind=SP)
Returned value of the Bessel Function calculation.
Calls
Called by
Call graph
bessim0 calls poly
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
bessim calls bessim0