bessj0 – PLUME
bessj0 Function
23 statements
public function bessj0(x)
Uses
nrutil_trim
nrtype
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(in) :: x
Return Value real(kind=SP)
Calls
Called by
Call graph
bessj0 calls poly
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
bessj_s calls bessj0
bess0_s_prime calls bessj_s
calc_fs1 calls bessj_s, bess0_s_prime
compute_fpc_cart calls calc_fs1, calc_wparth
compute_fpc_gyro calls calc_fs1
wparth_from_ratio calls calc_fs1
calc_wparth calls wparth_from_ratio
plume calls compute_fpc_cart, compute_fpc_gyro