bessel – PLUME
bessel Function
18 statements
public function bessel(n, x)
Uses
bessels
Call the correct Numerical Recipes Bessel function bessels is a function which calls the numerical recipes routine of the appropriate order -- this is to avoid to many if - then statements in the program. Note that we are determining I_n(x) e^(-x) to avoid large argument errors.
Arguments
Type Intent Optional Attributes Name
integer :: n
Bessel function order.
real :: x
Bessel function argument.
Return Value real
Calls
Called by
Call graph
bessel calls bessim, bessim0, bessim1
bessim calls bessim0, assert
bessim0 calls poly
bessim1 calls poly
assert calls assert1, assert2, assert3, assert4, assert_v
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
disp calls bessel
calc_eigen calls disp
map_search calls disp
om_double_scan calls disp, calc_eigen
om_radial calls disp, calc_eigen
om_scan calls disp, calc_eigen
test_disp calls disp
compute_fpc_cart calls calc_eigen
compute_fpc_gyro calls calc_eigen
map_scan calls map_search
radial_scan calls om_radial
plume calls map_search, om_double_scan, om_scan, test_disp, compute_fpc_cart, compute_fpc_gyro, map_scan, radial_scan