bess0_s_prime – PLUME
bess0_s_prime Function
8 statements
public function bess0_s_prime(x)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x
Return Value real
Calls
Called by
Call graph
bess0_s_prime calls bessj_s
bessj_s calls bessj0, bessj1
bessj0 calls poly
bessj1 calls poly
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
calc_fs1 calls bess0_s_prime
compute_fpc_cart calls calc_fs1, calc_wparth
compute_fpc_gyro calls calc_fs1
wparth_from_ratio calls calc_fs1
calc_wparth calls wparth_from_ratio
plume calls compute_fpc_cart, compute_fpc_gyro