bessim – PLUME
bessim Function
31 statements
public function bessim(n, x)
Uses
nrtype
nrutil_trim
Calculates the Modified Bessel Function of arbitrary order. Determines I_n(x) e^(-x) instead of I_n(x) to avoid large argument problems.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4B), intent(in) :: n
Order of Modified Bessel Function.
real(kind=SP), intent(in) :: x
Order of Modified Bessel Function.
Return Value real(kind=SP)
Returned value of the Bessel Function calculation.
Calls
Called by
Call graph
bessim calls assert, bessim0
assert calls assert1, assert2, assert3, assert4, assert_v
bessim0 calls poly
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
bessel calls bessim
disp calls bessel
calc_eigen calls disp
map_search calls disp
om_double_scan calls disp, calc_eigen
om_radial calls disp, calc_eigen
om_scan calls disp, calc_eigen
test_disp calls disp, calc_eigen
compute_fpc_cart calls calc_eigen
compute_fpc_gyro calls calc_eigen
map_scan calls map_search
radial_scan calls om_radial
plume calls map_search, om_double_scan, om_scan, test_disp, compute_fpc_cart, compute_fpc_gyro, map_scan, radial_scan