calc_fs1 – PLUME
calc_fs1 Subroutine
109 statements
private subroutine calc_fs1(omega, vperp, vpar, phi, ef, bf, hatV_s, q_s, aleph_s, tau_s, mu_s, aleph_r, elecdircontribution, exbar, fs0, fs1, epsSokhotski_Plemelj)
Uses
vars
bessels
nrtype
Determine species perturbed VDF fs1 at given (vperp,vpar,phi)
Arguments
Type Intent Optional Attributes Name
complex, intent(in) :: omega
Complex Frequency
real, intent(in) :: vperp
normalized velocity space
real, intent(in) :: vpar
normalized velocity space
real, intent(in) :: phi
azimuthal angle in velocity space
complex, intent(in), dimension(1:3) :: ef
E, B eigenfunctions in all 3 directions
complex, intent(in), dimension(1:3) :: bf
E, B eigenfunctions in all 3 directions
real, intent(in) :: hatV_s
Drift velocity norm to wpar_s
real, intent(in) :: q_s
normalized species charge
real, intent(in) :: aleph_s
T_perp/T_parallel_s
real, intent(in) :: tau_s
T_ref/T_s|_parallel
real, intent(in) :: mu_s
m_ref/m_s
real, intent(in) :: aleph_r
T_perp/T_parallel_R
real, intent(in) :: elecdircontribution
Sets components of Electric field (0 (DEFAULT) (or any other value) = Do not modify, 1=Keep only Ex(i.e.Eperp1), 2=Keep only Ey(i.e.Eperp2), 3=Keep only Ez(i.e.Epar))
complex, intent(in) :: exbar
normalizaiton factor
real, intent(in) :: fs0
normalized zero order distribution
complex, intent(out) :: fs1
first order distribution
real, intent(in) :: epsSokhotski_Plemelj
Small value for Sokhotski_Plemelj when computing moments of fs1; zero when just computing fs1
Calls
Called by
Call graph
calc_fs1 calls bess0_s_prime, bessj_s
bess0_s_prime calls bessj_s
bessj_s calls bessj0, bessj1
bessj0 calls poly
bessj1 calls poly
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
compute_fpc_cart calls calc_fs1, calc_wparth
compute_fpc_gyro calls calc_fs1
wparth_from_ratio calls calc_fs1
calc_wparth calls wparth_from_ratio
plume calls compute_fpc_cart, compute_fpc_gyro