calc_eigen – PLUME
calc_eigen Subroutine
137 statements
public subroutine calc_eigen(omega, electric, magnetic, vmean, ns, Ps, Ps_split, Ps_split_new, eigen_L, heat_L)
Uses
vars
Calculates the electric and magnetic fields as well as species velocities and density fluctuations for identified wave as well as the power emission or absorption.
Passed!!
GGH: 1/18/23
Arguments
Type Intent Optional Attributes Name
complex :: omega
Complex Frequency of identified wave.
complex, intent(out), dimension(1:3) :: electric
Complex electric field fluctuations (Ex, Ey, Ez)
complex, intent(out), dimension(1:3) :: magnetic
Complex magnetic field fluctuations (Bx, By, Bz)
complex, intent(out), dimension(1:3,1:nspec) :: vmean
Complex Velocity fluctuations: (Uxs, Uys, Uzs)
complex, intent(out), dimension(1:nspec) :: ns
Complex Density fluctuations.
real, intent(out), dimension(1:nspec) :: Ps
Power into/out of species/components.
real, intent(out), dimension(1:4,1:nspec) :: Ps_split
Power into/out of species
real, intent(out), dimension(1:6,1:nspec) :: Ps_split_new
<<<GGH: 1/18/23 Power into/out of species/components from LD, TTD, CD.
logical :: eigen_L
Logical for calculating eigenvalues
logical :: heat_L
Logical for calculating heating
Calls
Called by
Call graph
calc_eigen calls disp
disp calls bessel, zet_in
bessel calls bessim, bessim0, bessim1
zet_in calls zetout
bessim calls bessim0, assert
bessim0 calls poly
bessim1 calls poly
zetout calls cexp, float
assert calls assert1, assert2, assert3, assert4, assert_v
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
compute_fpc_cart calls calc_eigen
compute_fpc_gyro calls calc_eigen
om_double_scan calls calc_eigen
om_radial calls calc_eigen
om_scan calls calc_eigen
radial_scan calls om_radial
plume calls compute_fpc_cart, compute_fpc_gyro, om_double_scan, om_scan, radial_scan