calc_wparth – PLUME
calc_wparth Subroutine
10 statements
private subroutine calc_wparth(omega, wparth, is, ef)
Uses
vars
wrapper function to compute dimensional thermal velocity
Arguments
Type Intent Optional Attributes Name
complex, intent(in) :: omega
freq of solution
complex, intent(out) :: wparth
dimensional parallel thermal velocity
integer :: is
Spec conter
complex, dimension(1:3) :: ef
electric eigenmode
Calls
Called by
Call graph
calc_wparth calls wparth_from_ratio
wparth_from_ratio calls calc_fs1, fs0hat
calc_fs1 calls bess0_s_prime, bessj_s
bess0_s_prime calls bessj_s
bessj_s calls bessj0, bessj1
bessj0 calls poly
bessj1 calls poly
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
compute_fpc_cart calls calc_wparth
plume calls compute_fpc_cart