compute_fpc_cart – PLUME
compute_fpc_cart Subroutine
635 statements
public subroutine compute_fpc_cart(wrootindex)
Uses
vars
disprels
Computes the FPC associated with the linear fs1 and eigenfunction response on a square cartesian grid and writes FPC to file
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: wrootindex
Index of the root to compute fs1 and FPC for
Calls
Called by
Call graph
compute_fpc_cart calls calc_eigen, calc_fs1, calc_wparth, check_nbesmax, fs0hat, rtsec
calc_eigen calls disp
calc_fs1 calls bess0_s_prime, bessj_s
calc_wparth calls wparth_from_ratio
bess0_s_prime calls bessj_s
bessj_s calls bessj0, bessj1
disp calls disp0, disp1
wparth_from_ratio calls calc_fs1, fs0hat
bessj0 calls poly
bessj1 calls poly
disp0 calls bessel, zet_in
disp1 calls bessel, zet_in
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
bessel calls bessim, bessim0, bessim1
zet_in calls zetout
bessim calls bessim0, assert
bessim0 calls poly
bessim1 calls poly
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
zetout calls cexp, float
assert calls assert1, assert2, assert3, assert4, assert_v
plume calls compute_fpc_cart