disp – PLUME
disp Function
15 statements
public function disp(om)
Uses
vars
Hot, collisionless dispersion relation Hot plasma dispersion relation with weak neutral-charged collisions
Arguments
Type Intent Optional Attributes Name
complex :: om
Complex Frequency
Return Value complex
Calls
Called by
Call graph
disp calls disp0, disp1
disp0 calls bessel, zet_in
disp1 calls bessel, zet_in
bessel calls bessim, bessim0, bessim1
zet_in calls zetout
bessim calls bessim0, assert
bessim0 calls poly
bessim1 calls poly
zetout calls cexp, float
assert calls assert1, assert2, assert3, assert4, assert_v
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
calc_eigen calls disp
map_search calls disp
om_double_scan calls disp, calc_eigen
om_radial calls disp, calc_eigen
om_scan calls disp, calc_eigen
test_disp calls disp, calc_eigen
compute_fpc_cart calls calc_eigen
compute_fpc_gyro calls calc_eigen
map_scan calls map_search
radial_scan calls om_radial
plume calls map_search, om_double_scan, om_scan, test_disp, compute_fpc_cart, compute_fpc_gyro, map_scan, radial_scan