fs0hat – PLUME
fs0hat Function
9 statements
public function fs0hat(vperp, vpar, hatV_s, aleph_s)
Determines dimensionless species equilibrium VDF \hat{fs0} at (vperp,vpar)
Arguments
Type Intent Optional Attributes Name
real :: vperp
normalized velocity space
real :: vpar
normalized velocity space
real :: hatV_s
normalized species drift velocity by wpar_s
real :: aleph_s
T_perp/T_parallel_s
Return Value real
Called by
Call graph
compute_fpc_cart calls fs0hat, calc_wparth
compute_fpc_gyro calls fs0hat
wparth_from_ratio calls fs0hat
calc_wparth calls wparth_from_ratio
plume calls compute_fpc_cart, compute_fpc_gyro