get_runname – PLUME
get_runname Subroutine
11 statements
private subroutine get_runname(runname)
Get runname for output files from input argument by trimming '.in'.
Arguments
Type Intent Optional Attributes Name
character(len=50), intent(out) :: runname
Argument trimmed of '.in' string.
Called by
Call graph
read_guess_input calls get_runname
read_in_params calls get_runname
read_map_input calls get_runname
read_radial_input calls get_runname
read_scan_input calls get_runname
plume calls read_guess_input, read_in_params, read_map_input, read_radial_input, read_scan_input