get_unused_unit – PLUME
get_unused_unit Subroutine
11 statements
public subroutine get_unused_unit(unit)
Find a I/O unit that is not currently open.
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: unit
Called by
Call graph
get_indexed_namelist_unit calls get_unused_unit
om_double_scan calls get_unused_unit
om_scan calls get_unused_unit
radial_scan calls get_unused_unit
read_guess_input calls get_unused_unit, get_indexed_namelist_unit
read_in_params calls get_unused_unit, get_indexed_namelist_unit
read_map_input calls get_unused_unit
read_radial_input calls get_unused_unit
read_scan_input calls get_unused_unit, get_indexed_namelist_unit
plume calls om_double_scan, om_scan, radial_scan, read_guess_input, read_in_params, read_map_input, read_radial_input, read_scan_input