map_scan – PLUME
map_scan Subroutine
87 statements
public subroutine map_scan()
Uses
vars
Calculate complex frequency maps for scanned parameters. Intervatively calls map_search over a fixed range of parameters. k_1|=swf k_1|=swf
Arguments
None
Calls
Called by
Call graph
map_scan calls map_search, set_map_pointers
map_search calls disp, find_minima, rtsec
disp calls disp0, disp1
disp0 calls bessel, zet_in
disp1 calls bessel, zet_in
bessel calls bessim, bessim0, bessim1
zet_in calls zetout
bessim calls bessim0, assert
bessim0 calls poly
bessim1 calls poly
zetout calls cexp, float
assert calls assert1, assert2, assert3, assert4, assert_v
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
plume calls map_scan