om_double_scan – PLUME
om_double_scan Subroutine
266 statements
public subroutine om_double_scan()
Uses
vars
functions
Calculate solutions as a function of the variation of two parameters, creating a surface in parameter space. k_1|=swf
GGH: 1/18/23
GGH: 1/18/23
GGH: 1/18/23 GGH: 1/18/23
Arguments
None
Calls
Called by
Call graph
om_double_scan calls calc_eigen, disp, get_double_out_name, get_unused_unit, rtsec
calc_eigen calls disp
disp calls disp0, disp1
disp0 calls bessel, zet_in
disp1 calls bessel, zet_in
bessel calls bessim, bessim0, bessim1
zet_in calls zetout
bessim calls bessim0, assert
bessim0 calls poly
bessim1 calls poly
zetout calls cexp, float
assert calls assert1, assert2, assert3, assert4, assert_v
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
plume calls om_double_scan