om_radial – PLUME
om_radial Subroutine
43 statements
private subroutine om_radial(omlast, params, out_unit, fmt, out_type, ir, mod_write)
Uses
vars
Scans roots at a given location in parameter space. Used in conjunction with radial_scan.
Arguments
Type Intent Optional Attributes Name
complex, dimension(1:nspec) :: omlast
Arrays with complex frequency for each solution.
real, dimension(1:6,1:nspec) :: params
Species parameters:
integer, dimension(1:nroot_max) :: out_unit
Main output unit.
character(len=100) :: fmt
Output format for dispersion relation.
integer :: out_type
logic for outputing supplementary eigenfunction and heating calculations. 0: Frequency, Eigenfuction, Heating. 1: Frequency, Eigenfuction. 2: Frequency, Heating. 3: Frequency.
integer :: ir
Radial index.
logical :: mod_write
For only writing out every n_scan, not n_scan * n_res steps species parameters: useful for outputing data (INVESTIGATE THIS...)
Calls
Called by
Call graph
om_radial calls calc_eigen, disp, rtsec
calc_eigen calls disp
disp calls disp0, disp1
disp0 calls bessel, zet_in
disp1 calls bessel, zet_in
bessel calls bessim, bessim0, bessim1
zet_in calls zetout
bessim calls bessim0, assert
bessim0 calls poly
bessim1 calls poly
zetout calls cexp, float
assert calls assert1, assert2, assert3, assert4, assert_v
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
radial_scan calls om_radial
plume calls radial_scan