poly_rrv – PLUME
poly_rrv Function
19 statements
public function poly_rrv(x, coeffs)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(in), DIMENSION(:) :: x
real(kind=SP), intent(in), DIMENSION(:) :: coeffs
Return Value real(kind=SP), DIMENSION(size(x))
Calls
Called by
Call graph
poly_rrv calls poly_rr
poly calls poly_rrv, poly_msk_rrv
poly_msk_rrv calls poly_rrv
bessim0 calls poly
bessim1 calls poly
bessj0 calls poly
bessj1 calls poly
bessim calls bessim0
bessj_s calls bessj0, bessj1
bess0_s_prime calls bessj_s
calc_fs1 calls bessj_s, bess0_s_prime
compute_fpc_cart calls calc_fs1, calc_wparth
compute_fpc_gyro calls calc_fs1
wparth_from_ratio calls calc_fs1
calc_wparth calls wparth_from_ratio
plume calls compute_fpc_cart, compute_fpc_gyro