poly_dd – PLUME
poly_dd Function
31 statements
public function poly_dd(x, coeffs)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: x
real(kind=DP), intent(in), DIMENSION(:) :: coeffs
Return Value real(kind=DP)
Called by
Call graph
poly calls poly_dd, poly_ddv, poly_msk_ddv
poly_ddv calls poly_dd
bessim0 calls poly
bessim1 calls poly
bessj0 calls poly
bessj1 calls poly
poly_msk_ddv calls poly_ddv
bessim calls bessim0
bessj_s calls bessj0, bessj1
bess0_s_prime calls bessj_s
calc_fs1 calls bessj_s, bess0_s_prime
compute_fpc_cart calls calc_fs1, calc_wparth
compute_fpc_gyro calls calc_fs1
wparth_from_ratio calls calc_fs1
calc_wparth calls wparth_from_ratio
plume calls compute_fpc_cart, compute_fpc_gyro