poly_rr – PLUME
poly_rr Function
31 statements
public function poly_rr(x, coeffs)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(in) :: x
real(kind=SP), intent(in), DIMENSION(:) :: coeffs
Return Value real(kind=SP)
Called by
Call graph
poly calls poly_rr, poly_rrv, poly_msk_rrv
poly_rrv calls poly_rr
bessim0 calls poly
bessim1 calls poly
bessj0 calls poly
bessj1 calls poly
poly_msk_rrv calls poly_rrv
bessel calls bessim0, bessim1, bessim
bessim calls bessim0
bessj_s calls bessj0, bessj1
bess0_s_prime calls bessj_s
calc_fs1 calls bessj_s, bess0_s_prime
disp calls bessel
calc_eigen calls disp
compute_fpc_cart calls calc_fs1, calc_eigen, calc_wparth
compute_fpc_gyro calls calc_fs1, calc_eigen
map_search calls disp
om_double_scan calls disp, calc_eigen
om_radial calls disp, calc_eigen
om_scan calls disp, calc_eigen
test_disp calls disp
wparth_from_ratio calls calc_fs1
calc_wparth calls wparth_from_ratio
map_scan calls map_search
radial_scan calls om_radial
plume calls compute_fpc_cart, compute_fpc_gyro, map_search, om_double_scan, om_scan, test_disp, map_scan, radial_scan