poly_msk_rrv – PLUME
poly_msk_rrv Function
6 statements
public function poly_msk_rrv(x, coeffs, mask)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(in), DIMENSION(:) :: x
real(kind=SP), intent(in), DIMENSION(:) :: coeffs
logical(kind=LGT), intent(in), DIMENSION(:) :: mask
Return Value real(kind=SP), DIMENSION(size(x))
Calls
Called by
Call graph
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
poly calls poly_msk_rrv
bessim0 calls poly
bessim1 calls poly
bessj0 calls poly
bessj1 calls poly
bessel calls bessim0, bessim1, bessim
bessim calls bessim0
bessj_s calls bessj0, bessj1
bess0_s_prime calls bessj_s
calc_fs1 calls bessj_s, bess0_s_prime
disp0 calls bessel
disp1 calls bessel
compute_fpc_cart calls calc_fs1, calc_eigen, calc_wparth
compute_fpc_gyro calls calc_fs1, calc_eigen
disp calls disp0, disp1
wparth_from_ratio calls calc_fs1
calc_eigen calls disp
calc_wparth calls wparth_from_ratio
map_search calls disp
om_double_scan calls disp, calc_eigen
om_radial calls disp, calc_eigen
om_scan calls disp, calc_eigen
test_disp calls disp, calc_eigen
plume calls compute_fpc_cart, compute_fpc_gyro, map_search, om_double_scan, om_scan, test_disp, map_scan, radial_scan
map_scan calls map_search
radial_scan calls om_radial