radial_scan – PLUME
radial_scan Subroutine
290 statements
public subroutine radial_scan()
Uses
functions
vars
Calculates normal modes of the system for a specified radial solar wind model (under development) ADD split power calculations here... (KGK)
Arguments
None
Calls
Called by
Call graph
radial_scan calls get_unused_unit, om_radial
om_radial calls calc_eigen, disp, rtsec
calc_eigen calls disp
disp calls disp0, disp1
disp0 calls bessel, zet_in
disp1 calls bessel, zet_in
bessel calls bessim, bessim0, bessim1
zet_in calls zetout
bessim calls bessim0, assert
bessim0 calls poly
bessim1 calls poly
zetout calls cexp, float
assert calls assert1, assert2, assert3, assert4, assert_v
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
plume calls radial_scan