read_in_params – PLUME
read_in_params Subroutine
44 statements
public subroutine read_in_params()
Uses
vars
Read in system parameters. Input file is argument after executable: $ ./plume.e example.in
Arguments
None
Calls
Called by
Namelists
Namelist params
Variables
Name Type Default Description
betap real None
Reference Species Parallel Thermal-to-Magnetic Pressure Ratio. 8 pi n_ref T_ref,par/B^2
kperp real None
Wavenumber perpendicular to B0, normalized to reference gyroradius. k_perp rho_ref = k_perp w_perp,ref/Omega_ref
kpar real None
Wavenumber parallel to B0, normalized to reference gyroradius. k_perp rho_ref = k_perp w_t,ref,perp/Omega_ref
vtp real None
Parallel reference thermal velocity normalized to the speed of light. v_t,ref,par/c
nspec integer None
Number of species/components to be included in calculation.
nscan integer 0
Number of parameter scans.
option integer None
Selection for the type of dispersion calculation to be undertaken. -1: Calculate disp(om) at a single (omega, gamma) 0: Calculate Roots for input plasma parameters. 1: Calculate Roots for input plasma parameters or Reads in root value and then scan over plasma parameters, with range and type specified in .in file. 2: Calculate Roots for input plasma parameters or Reads in root value and then scan over two-dimensional plasma parameters space, with range and type specified in .in file. 3: deprecated 4: Make multiple maps of complex frequency space. 5: Find roots for parameters along a prescribed path Path is set by solar wind models, with values calculated and output by helper function (in development, the radial scan function.).
nroot_max integer None
Input specified nroots to follow.
use_map logical None
Determines method for selecting initial solutions. T-> Use map routine to determine solutions in defined regions of complex frequency space. Map parameters determined by &maps list in .in file. F-> Read nroot_max initial guesses for complex frequency solutions. Guesses determined by &guess_N lists in .in file.
low_n logical .true.
Toggle on low-n susceptibility suplementary calculation. 25-09-08: Deprecated 'new_low_n' variable, as that is now the only version of the n=0, \pm 1 calculation we wish to perform.
writeOut logical None
Enables or suppressed output to screen.
dataName character(len=100) None
Data Subdirectory where output is stored.
outputName character(len=100) None
Common name string for output files.
Namelist fpc
Variables
Name Type Default Description
vperpmin real None
vperpmax real None
vparmin real None
vparmax real None
delv real None
vxmin real None
vxmax real None
vymin real None
vymax real None
vzmin real None
vzmax real None
elecdircontribution real None
Call graph
read_in_params calls get_indexed_namelist_unit, get_runname, get_unused_unit, spec_read
get_indexed_namelist_unit calls get_unused_unit, input_unit, input_unit_exist
plume calls read_in_params