read_radial_input – PLUME
read_radial_input Subroutine
107 statements
public subroutine read_radial_input()
Uses
vars
Read in parameters for radial solar wind model scan. (in development).
Arguments
None
Calls
Called by
Call graph
read_radial_input calls get_runname, get_unused_unit, radial_read, radial_read_0, radial_read_1, radial_read_2, radial_read_3, radial_read_4, radial_read_5, radial_read_6
plume calls read_radial_input