read_map_input – PLUME
read_map_input Subroutine
11 statements
public subroutine read_map_input()
Uses
vars
Read in parameters for bounds on mapping dispersion roots. Invokes map_read.
Arguments
None
Calls
Called by
Call graph
read_map_input calls get_runname, get_unused_unit, map_read
plume calls read_map_input