rtsec – PLUME
rtsec Function
51 statements
public function rtsec(func, x1, x2, xacc, iflag)
Secant routine to find minimum value of dispersion relation function.
Arguments
Type Intent Optional Attributes Name
complex :: func
Function to evaluate.
complex :: x1
Lower bracket value of solution refinement.
complex :: x2
Upper bracket value of solution refinement.
real :: xacc
Solution tolerance.
integer :: iflag
flag for tracking iteration.
Return Value complex
Called by
Call graph
compute_fpc_cart calls rtsec
compute_fpc_gyro calls rtsec
map_search calls rtsec
om_double_scan calls rtsec
om_radial calls rtsec
om_scan calls rtsec
refine_guess calls rtsec
map_scan calls map_search
radial_scan calls om_radial
plume calls compute_fpc_cart, compute_fpc_gyro, map_search, om_double_scan, om_scan, refine_guess, map_scan, radial_scan