wparth_from_ratio – PLUME
wparth_from_ratio Function
103 statements
public function wparth_from_ratio(is, ef)
Uses
vars
disprels
(this is basically just a stray minus sign...)
Arguments
Type Intent Optional Attributes Name
integer :: is
species loop counter
complex, dimension(1:3) :: ef
electric field eigenmode
Return Value complex
Calls
Called by
Call graph
wparth_from_ratio calls calc_fs1, fs0hat
calc_fs1 calls bess0_s_prime, bessj_s
bess0_s_prime calls bessj_s
bessj_s calls bessj0, bessj1
bessj0 calls poly
bessj1 calls poly
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
calc_wparth calls wparth_from_ratio
compute_fpc_cart calls calc_wparth
plume calls compute_fpc_cart