zet_in – PLUME
zet_in Function
9 statements
public function zet_in(kpar, zin)
Evaluate Plasma Dispersion Function (Z) for kparallel >/< 0 Calls zetout with appropriate argument.
Arguments
Type Intent Optional Attributes Name
real :: kpar
complex :: zin
Argument of plasma dispersion function.
Return Value complex
Value of plasma dispersion function.
Calls
Called by
Call graph
zet_in calls zetout
zetout calls cexp, float
disp calls zet_in
calc_eigen calls disp
map_search calls disp
om_double_scan calls disp, calc_eigen
om_radial calls disp, calc_eigen
om_scan calls disp, calc_eigen
test_disp calls disp, calc_eigen
compute_fpc_cart calls calc_eigen
compute_fpc_gyro calls calc_eigen
map_scan calls map_search
radial_scan calls om_radial
plume calls map_search, om_double_scan, om_scan, test_disp, compute_fpc_cart, compute_fpc_gyro, map_scan, radial_scan