assert – PLUME
assert Interface
3 statements
public interface assert
Calls
Called by
Module Procedures
public subroutine assert1(n1, string)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: n1
character(len=*), intent(in) :: string
public subroutine assert2(n1, n2, string)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: n1
logical, intent(in) :: n2
character(len=*), intent(in) :: string
public subroutine assert3(n1, n2, n3, string)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: n1
logical, intent(in) :: n2
logical, intent(in) :: n3
character(len=*), intent(in) :: string
public subroutine assert4(n1, n2, n3, n4, string)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: n1
logical, intent(in) :: n2
logical, intent(in) :: n3
logical, intent(in) :: n4
character(len=*), intent(in) :: string
public subroutine assert_v(n, string)
Arguments
Type Intent Optional Attributes Name
logical, intent(in), DIMENSION(:) :: n
character(len=*), intent(in) :: string
Call graph
assert calls assert1, assert2, assert3, assert4, assert_v
bessim calls assert
bessel calls bessim
disp calls bessel
calc_eigen calls disp
map_search calls disp
om_double_scan calls disp, calc_eigen
om_radial calls disp, calc_eigen
om_scan calls disp, calc_eigen
test_disp calls disp
compute_fpc_cart calls calc_eigen
compute_fpc_gyro calls calc_eigen
map_scan calls map_search
radial_scan calls om_radial
plume calls map_search, om_double_scan, om_scan, test_disp, compute_fpc_cart, compute_fpc_gyro, map_scan, radial_scan