poly – PLUME
poly Interface
3 statements
public interface poly
Calls
Called by
Module Procedures
public function poly_rr(x, coeffs)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(in) :: x
real(kind=SP), intent(in), DIMENSION(:) :: coeffs
Return Value real(kind=SP)
public function poly_rrv(x, coeffs)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(in), DIMENSION(:) :: x
real(kind=SP), intent(in), DIMENSION(:) :: coeffs
Return Value real(kind=SP), DIMENSION(size(x))
public function poly_dd(x, coeffs)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: x
real(kind=DP), intent(in), DIMENSION(:) :: coeffs
Return Value real(kind=DP)
public function poly_ddv(x, coeffs)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in), DIMENSION(:) :: x
real(kind=DP), intent(in), DIMENSION(:) :: coeffs
Return Value real(kind=DP), DIMENSION(size(x))
public function poly_rc(x, coeffs)
Arguments
Type Intent Optional Attributes Name
complex(kind=SPC), intent(in) :: x
real(kind=SP), intent(in), DIMENSION(:) :: coeffs
Return Value complex(kind=SPC)
public function poly_cc(x, coeffs)
Arguments
Type Intent Optional Attributes Name
complex(kind=SPC), intent(in) :: x
complex(kind=SPC), intent(in), DIMENSION(:) :: coeffs
Return Value complex(kind=SPC)
public function poly_msk_rrv(x, coeffs, mask)
Arguments
Type Intent Optional Attributes Name
real(kind=SP), intent(in), DIMENSION(:) :: x
real(kind=SP), intent(in), DIMENSION(:) :: coeffs
logical(kind=LGT), intent(in), DIMENSION(:) :: mask
Return Value real(kind=SP), DIMENSION(size(x))
public function poly_msk_ddv(x, coeffs, mask)
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in), DIMENSION(:) :: x
real(kind=DP), intent(in), DIMENSION(:) :: coeffs
logical(kind=LGT), intent(in), DIMENSION(:) :: mask
Return Value real(kind=DP), DIMENSION(size(x))
Call graph
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr
bessim0 calls poly
bessim1 calls poly
bessj0 calls poly
bessj1 calls poly
bessim calls bessim0
bessj_s calls bessj0, bessj1
bess0_s_prime calls bessj_s
calc_fs1 calls bessj_s, bess0_s_prime
compute_fpc_cart calls calc_fs1, calc_wparth
compute_fpc_gyro calls calc_fs1
wparth_from_ratio calls calc_fs1
calc_wparth calls wparth_from_ratio
plume calls compute_fpc_cart, compute_fpc_gyro