plume – PLUME
plume Program
92 statements
Uses
fpc
vars
functions
disprels
Calls
Variables
Type Attributes Name Initial
integer :: is
Index for looping through parametric variations with om_scan.
integer :: iroot
Index for making many JET-PLUME signatures for each root
Call graph
plume calls compute_fpc_cart, compute_fpc_gyro, map_scan, map_search, om_double_scan, om_scan, radial_scan, read_guess_input, read_in_params, read_map_input, read_radial_input, read_scan_input, refine_guess, test_disp
compute_fpc_cart calls calc_eigen, calc_fs1, calc_wparth, check_nbesmax, fs0hat, rtsec
compute_fpc_gyro calls calc_eigen, calc_fs1, check_nbesmax, fs0hat, rtsec
map_scan calls map_search, set_map_pointers
map_search calls disp, find_minima, rtsec
om_double_scan calls calc_eigen, disp, get_double_out_name, get_unused_unit, rtsec
om_scan calls calc_eigen, disp, get_out_name, get_unused_unit, rtsec
radial_scan calls get_unused_unit, om_radial
read_guess_input calls get_indexed_namelist_unit, get_runname, get_unused_unit, om_read
read_in_params calls get_indexed_namelist_unit, get_runname, get_unused_unit, spec_read
read_map_input calls get_runname, get_unused_unit, map_read
read_radial_input calls get_runname, get_unused_unit, radial_read, radial_read_0, radial_read_1, radial_read_2, radial_read_3, radial_read_4, radial_read_5, radial_read_6
read_scan_input calls get_indexed_namelist_unit, get_runname, get_unused_unit, scan_read
refine_guess calls rtsec
test_disp calls calc_eigen, disp
calc_eigen calls disp
calc_fs1 calls bess0_s_prime, bessj_s
calc_wparth calls wparth_from_ratio
disp calls disp0, disp1
get_indexed_namelist_unit calls get_unused_unit, input_unit, input_unit_exist
om_radial calls calc_eigen, disp, rtsec
bess0_s_prime calls bessj_s
bessj_s calls bessj0, bessj1
disp0 calls bessel, zet_in
disp1 calls bessel, zet_in
wparth_from_ratio calls calc_fs1, fs0hat
bessel calls bessim, bessim0, bessim1
bessj0 calls poly
bessj1 calls poly
zet_in calls zetout
poly calls poly_cc, poly_dd, poly_ddv, poly_msk_ddv, poly_msk_rrv, poly_rc, poly_rr, poly_rrv
bessim calls bessim0, assert
bessim0 calls poly
bessim1 calls poly
zetout calls cexp, float
assert calls assert1, assert2, assert3, assert4, assert_v
poly_ddv calls poly_dd
poly_msk_ddv calls poly_ddv
poly_msk_rrv calls poly_rrv
poly_rrv calls poly_rr