---
name: Update ADS library with papers citing PLUME

on:
  schedule:
    # Midnight on every Sunday
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update_library:
    name: Update library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install script dependencies
        run: |
          pip install requests==2.31

      # Strict on the main repo: fail on 401 or any error
      - name: Run script (strict on main PLUME repo)
        if: ${{ github.repository == 'kgklein/PLUME' }}
        env:
          ADS_API_TOKEN: ${{ secrets.ADS_API_TOKEN }}
        run: |
          python .github/scripts/add_plume_papers_to_ads_library.py

      # Lenient on forks/your repo: ignore only 401 or missing token errors
      - name: Run script (lenient on forks)
        if: ${{ github.repository != 'kgklein/PLUME' }}
        env:
          ADS_API_TOKEN: ${{ secrets.ADS_API_TOKEN }}
        shell: bash
        run: |
          set -o pipefail
          python .github/scripts/add_plume_papers_to_ads_library.py 2>&1 | tee ads_run.log
          rc=${PIPESTATUS[0]}
          if [ $rc -ne 0 ]; then
            if grep -qiE '401|UNAUTHORIZED|Please set ADS_API_TOKEN' ads_run.log; then
              echo "::warning::ADS step skipped on ${GITHUB_REPOSITORY} (unauthorized or no token)."
              exit 0
            fi
          fi
          exit $rc

